App1/MyApp/MyApp/urls.py
from django.contrib import admin
from django.urls import path, include

handler404= 'MyApp.views.custom_page_not_found'

urlpatterns = [
    path("",include("blog.urls")),
    path('admin/', admin.site.urls),
]

App1/MyApp/blog/urls.py
from django.urls import path
from . import views

app_name="blog"

urlpatterns=[
    path("", views.index,name="index"),
    path("post/<str:slug>",views.detail,name="detail"),
    path("new_url_redirect",views.new_url_redirect,name="new_page_url"),
    path("old_url_redirect",views.old_url_redirect,name="old_url"),
    path("contacts",views.contacts,name="contact"),
    path("about",views.about,name="about")
]   

App1/MyApp/blog/models.py
from django.db import models
from django.utils.text import slugify

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    
    title=models.CharField(max_length=500)
    content=models.TextField()
    img_url=models.URLField(max_length=200,null=True)
    craeted=models.DateTimeField(auto_now_add=True)
    slug=models.SlugField(max_length=500,unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)


    def save(self, *args, **kwargs):
        self.slug=slugify(self.title)
        super().save(*args, **kwargs)


    def __str__(self):
        return self.title

class About(models.Model):
    content=models.TextField()



    

App1/MyApp/blog/forms.py
from django import forms

class ContactForms(forms.Form):
    name=forms.CharField(label='Name', max_length=100,required=True)
    email=forms.EmailField(label='Email',required=True)
    message=forms.CharField(label='Message',required=True)

App1/MyApp/MyApp/views.py
from django.shortcuts import render

def custom_page_not_found(request,exception):
    return render(request,'404.html',status=404)

App1/MyApp/blog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,Http404
from django.urls import reverse
import logging
from .models import Post, About
from django.core.paginator import Paginator
from .forms import ContactForms

# Create your views here.

#static demo data

# posts=[
#         {'id':1,'title':'VK hits Six','content':'Sports'},
#         {'id':2,'title':'School Reopening Announcement','content':'Education'},
#         {'id':3,'title':'New style Dodthis','content':'Fashion'},
#         {'id':4,'title':'Nano Science demand increases','content':'Science'},
#         {'id':5,'title':'AI tunrs into AGI','content':'Technology'},
#         {'id':6,'title':'No GST upto 12LPA salary','content':'Commerce'},
#         {'id':7,'title':'Organic producers needed','content':'Food'},
#         {'id':8,'title':'Cancer medicine introduced in Russian market','content':'Health'},
#         {'id':9,'title':'Pongal winner Madhagajaraja','content':'Entertainment'},
#         {'id':10,'title':'Next gen 39T launch','content':'Automobile'},
#     ]




def index(request):
    blog_title="ADM Posts"  
    #getting data from model
    all_posts=Post.objects.all() 

    #Paginator
    paginator=Paginator(all_posts,6)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)


    return render(request,'blog/index.html',{'blok_titke':blog_title,'page_obj':page_obj})

def detail(request,slug):
    
    #sample
    # post=next((item for item in posts if item['id']==post_id),None)
    

    #logger
    # logger=logging.getLogger("TESTING")
    # logger.debug(f'Post id={post}')

    try:
        post=Post.objects.get(slug=slug)
        related_post=Post.objects.filter(category=post.category).exclude(pk=post.id)
    
    except Post.DoesNotExist:
        raise Http404("Post Does not Exist!")

    return render(request,'blog/detail.html',{"post":post,"related_post":related_post})

def old_url_redirect(request):
    return redirect(reverse("blog:new_page_url"))

def new_url_redirect(request):
    return HttpResponse("HI NEW URL")


def contacts(request):

    if request.method == 'POST':
        form = ContactForms(request.POST)
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        logger=logging.getLogger("TESTING")
        if form.is_valid():
            # form.cleaned_data['name']
            # print("Form is valid")
            
            logger.debug(f"POST {form.cleaned_data['name']} {form.cleaned_data['email']} {form.cleaned_data['message']}")
            success_msg="Your Email has been sent"
            return render(request,'blog/contacts.html',{'form':form,"success_msg":success_msg})

        else:
            print(f"Not valid form reason is {form.errors}")
            logger.debug(f'Form submission failure{form.errors}')
        
        return render(request,'blog/contacts.html',{'form':form,'name':name,'email':email,'message':message})
    return render(request,'blog/contacts.html')



def about(request):
    about_content=About.objects.first().content
    return render(request,"blog/about.html",{"about_content":about_content})

    

App1/MyApp/blog/templates/blog/about.html
{% extends "blog/base.html" %}

{%block content%}

<div class="container-fluid ">
    <h3>About Us</h3>
    <div class="d-flex gap-3 justify-content-center mt-5">
        <img src="https://picsum.photos/300/300" alt="">
        <div class="content">
        {{about_content}}    
        
        </div>
        
    </div>
</div>


{%endblock%}

App1/MyApp/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{post.content|default:'Home-Blog'}}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'blog/style.css'%}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
</head>
<body >
    <!-- header content'-->
     {% include "blog/includes/header.html" %}

    <!-- Dynamic conetent-->
     {%block content%}
     {% endblock %}

     <!-- Fotter content-->

     {%include "blog/includes/footer.html" %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

App1/MyApp/blog/templates/blog/contacts.html
{% extends "blog/base.html" %}

{%block content%}

    <div class="container-fluid ">
        <div class="d-flex justify-content-center mt-5">
            <div class="d-flex gap-3 flex-column">
                <h3>Contact Form</h3>
                <!-- Error Message-->
                {%for field in form%}
                    <div class="col-12">
                        {%if field.errors%}
                            <span class="fw-bold">  {{field.label_tag}}    </span>
                            {%for error in field.errors%}
                                <span class="text-danger">{{error}} </span>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}
                
                <!-- Success Message-->
                {%if success_msg%}
                <div class="alert alert-success" role="alert"> {{success_msg}}</div>
                {%endif%}

                <form method="POST" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-6">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{name}}">
                    </div>
                    <div class="col-md-6">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="email"  value="{{email}}">
                    </div>
                    <div class="col-12">
                        <label for="message" class="form-label" >Message</label>
                        <textarea class="form-control" id="message" name="message" rows="4" value="{{message}}" ></textarea>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
        
    </div>


{%endblock%}
   

App1/MyApp/blog/templates/blog/detail.html
{%extends "blog/base.html"%}

{%block content%}
<div class="container-fluid ">
       
        <div class="row">
            <div class="col-lg-8">
              <h1 class="mb-4">Post {{post.title|default:'Title'}} <small style="font-size:20px">({{post.category.name}})</small> </h1>
              <p class="text-muted">Posted on {{post.craeted|date:"l F j, Y"}}</p>
              <img src="{{post.img_url}}" class="img-fluid mb-4" alt="Blog Image">
              <p>{{post.content}}</p>
              
            </div>
            <div class="col-lg-4">
              <div class="card mt-3">
                <div class="card-body">
                  <h5 class="card-title">Related Posts</h5>
                  <ul class="list-unstyled">
                    
                    {% for related_post in related_post %}
                    <li><a href="{% url 'blog:detail' slug=related_post.slug %}">{{related_post.title}}</a></li>
                    {% endfor %}
                    
                  </ul>
                </div>
              </div>
            </div>
        </div>
</div>
{%endblock%}  

App1/MyApp/blog/templates/blog/includes/footer.html
<footer class="bg-dark text-light p-3" style="position: fixed; bottom: 0; width: 100%;">
    <div class="col-4 d-flex justify-content-center align-items-center">
      <span class="text-light">© 2025 ADM Company, Inc</span>
    </div>
</footer>

App1/MyApp/blog/templates/blog/includes/header.html
<header class="p-3 bg-dark text-white">
    <div class="row">
        <div class="col">
            <h3> <a class="text-light text-decoration-none" href='/blog'>{{blok_titke | default:"ADM Post"}}</h3>
        </div>
        <div class="col">
            <div class="d-flex justify-content-center gap-3">
                <a class="text-light text-decoration-none" href="/blog">Home</a>
                <a class="text-light text-decoration-none" href="/blog/about">About</a>
                <a class="text-light text-decoration-none" href="/blog/contacts">Contact</a>
            </div>
        </div>
    </div>
</header>

App1/MyApp/blog/templates/blog/index.html
    {% extends "blog/base.html" %}

    {%block content%}
    <div class="container-fluid ">
        <div class="row my-2">
            <div class="col">
                <h2 >Latest Posts</h2>
            </div>
            <div class="col-3">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search..." aria-label="Search">
                    <button class="btn btn-outline-light btn-primary " type="button" id="button-search">
                      <i class="bi bi-search"></i> <!-- Bootstrap Icons -->
                    </button>
                  </div>
            </div>
        </div>
        <div class="row m-3">
            {%if page_obj%}
            {% for post in page_obj %}
            <div class="col-4 mb-4">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                <img style="height=300,width=300" src="{{post.img_url}}" class="img-fluid" alt="...">
                            </div>
                            <div class="col-md-8">
                                <h5 class="card-title">{{post.title|default:"Post Title"|truncatewords:3}}</h5>
                                <p class="card-text">{{post.content|default:"Explore More"|truncatewords:10}}</p>
                                <div class="d-flex justify-content-between">
                                     
                                    {% comment %} <a class="text-decoration-none text-dark fw-bold" href="#"></a> {% endcomment %}
                                    <a href="{% url 'blog:detail' slug=post.slug %}">Read More</a>
                                    <a class="text-decoration-none text-dark fw-bold" href="#">{{post.category.name}}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

            {% if page_obj.has_other_pages %}
            <div class="col-12 my-3">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page=1" aria-label="First">
                                <span aria-hidden="true">&laquo; first</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
                                <span aria-hidden="true">previous</span>
                            </a>
                        </li>
                        {% endif %}
                        
                        <li class="page-item"><span class="page-link">Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span></li>
                                                
                        {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                                <span aria-hidden="true">next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.paginator.num_pages}}" aria-label="Last">
                                <span aria-hidden="true">last &raquo;</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
                
            </div>
            {%endif%}
            {% else%}
            <p>No content found</p>
            {% endif %}
        </div>
        <div class="row">
           
        </div>
        
    </div>
    {%endblock%}